<a href="https://colab.research.google.com/github/rafa-el-ferreira/Portuguese-League-25-26/blob/main/Task_M10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1st METRIC** **MAIN** **CODE**

In [3]:
#first install pandas
import pandas as pd

#Then do the Plain Request
import requests
import json

#import json_normalize()
from pandas import json_normalize

#Explore competitions
uri = 'https://api.football-data.org/v4/competitions/'
my_key = { 'X-Auth-Token': '--------------------' }

response = requests.get(uri, headers=my_key)

competitions = response.json()


#now this is the full request
competitions_final = json_normalize(competitions["competitions"])

**STARTING TO PEEL THE ONION**

In [4]:
#Now i'll try to get more info
type(competitions) #dictionary
competitions.keys()

dict_keys(['count', 'filters', 'competitions'])

In [33]:
#Check what's inside each key and after that explore it
#competitions["competitions"]

In [6]:
type(competitions["competitions"])

list

In [7]:
len(competitions["competitions"])

13

In [8]:
#see what's inside some index and can confirme each index corresponds a league
competitions["competitions"][1]

{'id': 2016,
 'area': {'id': 2072,
  'name': 'England',
  'code': 'ENG',
  'flag': 'https://crests.football-data.org/770.svg'},
 'name': 'Championship',
 'code': 'ELC',
 'type': 'LEAGUE',
 'emblem': 'https://crests.football-data.org/ELC.png',
 'plan': 'TIER_ONE',
 'currentSeason': {'id': 2416,
  'startDate': '2025-08-08',
  'endDate': '2026-05-12',
  'currentMatchday': 46,
  'winner': None},
 'numberOfAvailableSeasons': 9,
 'lastUpdated': '2026-05-11T15:45:39Z'}

No more onion to peel

In [9]:
#Now we use json_normalize to transform this list of dictionaries into a DataFrame to work it
#go back to MAIN CODE and write:
#from pandas import json_normalize
#competitions_final = json_normalize(competitions["competitions"])

In [10]:
competitions_final

,id,name,code,type,emblem,plan,numberOfAvailableSeasons,lastUpdated,area.id,area.name,...,currentSeason.winner.name,currentSeason.winner.shortName,currentSeason.winner.tla,currentSeason.winner.crest,currentSeason.winner.address,currentSeason.winner.website,currentSeason.winner.founded,currentSeason.winner.clubColors,currentSeason.winner.venue,currentSeason.winner.lastUpdated
0,2013,Campeonato Brasileiro Série A,BSA,LEAGUE,https://crests.football-data.org/bsa.png,TIER_ONE,10,2024-09-13T16:55:53Z,2032,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016,Championship,ELC,LEAGUE,https://crests.football-data.org/ELC.png,TIER_ONE,9,2026-05-11T15:45:39Z,2072,England,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,Premier League,PL,LEAGUE,https://crests.football-data.org/PL.png,TIER_ONE,127,2024-09-13T16:51:24Z,2072,England,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001,UEFA Champions League,CL,CUP,https://crests.football-data.org/CL.png,TIER_ONE,46,2024-09-13T16:53:48Z,2077,Europe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,European Championship,EC,CUP,https://crests.football-data.org/ec.png,TIER_ONE,17,2024-09-13T17:04:30Z,2077,Europe,...,Spain,Spain,ESP,https://crests.football-data.org/760.svg,"Ramón y Cajal, s/n Las Rozas 28230",http://www.rfef.es,1909.0,Red / Blue / Yellow,Estadio Alfredo Di Stéfano,2021-05-26T09:46:48Z
5,2015,Ligue 1,FL1,LEAGUE,https://crests.football-data.org/FL1.png,TIER_ONE,82,2024-09-13T16:49:18Z,2081,France,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2002,Bundesliga,BL1,LEAGUE,https://crests.football-data.org/BL1.png,TIER_ONE,63,2024-09-13T16:48:00Z,2088,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2019,Serie A,SA,LEAGUE,https://crests.football-data.org/c111.png,TIER_ONE,94,2026-01-02T11:22:51Z,2114,Italy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,Eredivisie,DED,LEAGUE,https://crests.football-data.org/ED.png,TIER_ONE,70,2024-09-13T16:34:42Z,2163,Netherlands,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2017,Primeira Liga,PPL,LEAGUE,https://crests.football-data.org/PPL.png,TIER_ONE,77,2024-09-13T16:54:08Z,2187,Portugal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2152,Copa Libertadores,CLI,CUP,https://crests.football-data.org/CLI.svg,TIER_FOUR,6,2026-05-20T00:07:05Z,2220,South America,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2014,Primera Division,PD,LEAGUE,https://crests.football-data.org/laliga.png,TIER_ONE,94,2024-09-13T16:52:33Z,2224,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2000,FIFA World Cup,WC,CUP,https://crests.football-data.org/wm26.png,TIER_ONE,23,2025-12-08T05:32:32Z,2267,World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
type(competitions_final)

pandas.core.frame.DataFrame

In [12]:
#we can see that this is a DataFrame, so here are some functions to explore it
competitions_final.head()
competitions_final.tail()
competitions_final.sample(3)
competitions_final.info() #a very important one to check if the Dtype is ok and if there are non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 28 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                13 non-null     int64
 1   name                              13 non-null     object
 2   code                              13 non-null     object
 3   type                              13 non-null     object
 4   emblem                            13 non-null     object
 5   plan                              13 non-null     object
 6   numberOfAvailableSeasons          13 non-null     int64
 7   lastUpdated                       13 non-null     object
 8   area.id                           13 non-null     int64
 9   area.name                         13 non-null     object
 10  area.code                         13 non-null     object
 11  area.flag                         12 non-null     object
 12  currentSeason.id                  13 non-null     int64
 13  currentSeason.startDate           13 non-null     object
 14  currentSeason.endDate             13 non-null     object
 15  currentSeason.currentMatchday     13 non-null     int64
 16  currentSeason.winner              0 non-null      float64
 17  currentSeason.winner.id           1 non-null      float64
 18  currentSeason.winner.name         1 non-null      object
 19  currentSeason.winner.shortName    1 non-null      object
 20  currentSeason.winner.tla          1 non-null      object
 21  currentSeason.winner.crest        1 non-null      object
 22  currentSeason.winner.address      1 non-null      object
 23  currentSeason.winner.website      1 non-null      object
 24  currentSeason.winner.founded      1 non-null      float64
 25  currentSeason.winner.clubColors   1 non-null      object
 26  currentSeason.winner.venue        1 non-null      object
 27  currentSeason.winner.lastUpdated  1 non-null      object
dtypes: float64(3), int64(5), object(20)
memory usage: 3.0+ KB

PORTUGUESE LEAGUE MATCHES MAIN CODE

In [13]:
uri = 'https://api.football-data.org/v4/competitions/PPL/matches'
my_key = { 'X-Auth-Token': '7972cc960161452182712a662c532115' }

response = requests.get(uri, headers=my_key)

matches = response.json()

PPL_matches = json_normalize(matches["matches"])

In [14]:
type(matches)

dict

In [15]:
matches.keys()

dict_keys(['filters', 'resultSet', 'competition', 'matches'])

In [16]:
#this is the information that we want and now we'll do the same process before
#matches["matches"]

In [17]:
len(matches["matches"])

306

In [18]:
type(matches["matches"])

list

In [19]:
#now use json_normalize and put it into the main code of the Portuguese League matches

json_normalize(matches["matches"])

,id,utcDate,status,matchday,stage,group,lastUpdated,referees,area.id,area.name,...,awayTeam.shortName,awayTeam.tla,awayTeam.crest,score.winner,score.duration,score.fullTime.home,score.fullTime.away,score.halfTime.home,score.halfTime.away,odds.msg
0,545700,2025-08-08T19:15:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Sporting CP,SPO,https://crests.football-data.org/498.png,AWAY_TEAM,REGULAR,0,2,0,1,Activate Odds-Package in User-Panel to retriev...
1,545706,2025-08-09T14:30:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Gil Vicente,GIL,https://crests.football-data.org/5533.png,AWAY_TEAM,REGULAR,0,2,0,2,Activate Odds-Package in User-Panel to retriev...
2,545703,2025-08-09T19:30:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,AVS,AVS,https://crests.football-data.org/10340.png,HOME_TEAM,REGULAR,3,1,1,0,Activate Odds-Package in User-Panel to retriev...
3,545707,2025-08-10T16:00:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Santa Clara,CD,https://crests.football-data.org/5530.png,HOME_TEAM,REGULAR,3,0,2,0,Activate Odds-Package in User-Panel to retriev...
4,545701,2025-08-10T19:30:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Tondela,TON,https://crests.football-data.org/1049.png,HOME_TEAM,REGULAR,3,0,2,0,Activate Odds-Package in User-Panel to retriev...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,546004,2026-05-16T17:00:00Z,FINISHED,34,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Tondela,TON,https://crests.football-data.org/1049.png,HOME_TEAM,REGULAR,3,1,1,0,Activate Odds-Package in User-Panel to retriev...
302,546005,2026-05-16T17:00:00Z,FINISHED,34,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Amadora,AMA,https://crests.football-data.org/9136.png,DRAW,REGULAR,2,2,1,1,Activate Odds-Package in User-Panel to retriev...
303,545998,2026-05-16T19:30:00Z,FINISHED,34,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Alverca,ALV,https://crests.football-data.org/7822.png,HOME_TEAM,REGULAR,1,0,0,0,Activate Odds-Package in User-Panel to retriev...
304,545999,2026-05-16T19:30:00Z,FINISHED,34,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Gil Vicente,GIL,https://crests.football-data.org/5533.png,HOME_TEAM,REGULAR,3,0,2,0,Activate Odds-Package in User-Panel to retriev...
305,546001,2026-05-16T19:30:00Z,FINISHED,34,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,SL Benfica,BEN,https://crests.football-data.org/1903.png,AWAY_TEAM,REGULAR,1,3,0,3,Activate Odds-Package in User-Panel to retriev...

In [20]:
#PPL_matches

In [21]:
#PPL_matches.info()

In [22]:
#holding on wins at home (win at HT and FT)

first_metric = PPL_matches[(PPL_matches["score.halfTime.home"] > PPL_matches["score.halfTime.away"]) & (PPL_matches["score.winner"] == "HOME_TEAM")]

In [23]:
first_metric

,id,utcDate,status,matchday,stage,group,lastUpdated,referees,area.id,area.name,...,awayTeam.shortName,awayTeam.tla,awayTeam.crest,score.winner,score.duration,score.fullTime.home,score.fullTime.away,score.halfTime.home,score.halfTime.away,odds.msg
2,545703,2025-08-09T19:30:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,AVS,AVS,https://crests.football-data.org/10340.png,HOME_TEAM,REGULAR,3,1,1,0,Activate Odds-Package in User-Panel to retriev...
3,545707,2025-08-10T16:00:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Santa Clara,CD,https://crests.football-data.org/5530.png,HOME_TEAM,REGULAR,3,0,2,0,Activate Odds-Package in User-Panel to retriev...
4,545701,2025-08-10T19:30:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Tondela,TON,https://crests.football-data.org/1049.png,HOME_TEAM,REGULAR,3,0,2,0,Activate Odds-Package in User-Panel to retriev...
7,545708,2025-08-11T19:45:00Z,FINISHED,1,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Vitória SC,GUI,https://crests.football-data.org/5543.png,HOME_TEAM,REGULAR,3,0,2,0,Activate Odds-Package in User-Panel to retriev...
15,545715,2025-08-17T19:30:00Z,FINISHED,2,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Arouca,FCA,https://crests.football-data.org/712.png,HOME_TEAM,REGULAR,6,0,3,0,Activate Odds-Package in User-Panel to retriev...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,545991,2026-05-10T17:00:00Z,FINISHED,33,REGULAR_SEASON,None,2026-05-26T00:20:43Z,"[{'id': 40454, 'name': 'Carlos Macedo', 'type'...",2187,Portugal,...,Porto,FCP,https://crests.football-data.org/503.png,HOME_TEAM,REGULAR,3,1,1,0,Activate Odds-Package in User-Panel to retriev...
292,545990,2026-05-11T19:15:00Z,FINISHED,33,REGULAR_SEASON,None,2026-05-11T23:24:13Z,"[{'id': 57144, 'name': 'Ricardo Baixinho', 'ty...",2187,Portugal,...,Moreirense,MOR,https://crests.football-data.org/583.png,HOME_TEAM,REGULAR,2,0,1,0,Activate Odds-Package in User-Panel to retriev...
295,545995,2026-05-11T19:15:00Z,FINISHED,33,REGULAR_SEASON,None,2026-05-26T00:20:43Z,"[{'id': 220533, 'name': 'Hélder Carvalho', 'ty...",2187,Portugal,...,CD Nacional,CDN,https://crests.football-data.org/5529.png,HOME_TEAM,REGULAR,2,0,1,0,Activate Odds-Package in User-Panel to retriev...
301,546004,2026-05-16T17:00:00Z,FINISHED,34,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Tondela,TON,https://crests.football-data.org/1049.png,HOME_TEAM,REGULAR,3,1,1,0,Activate Odds-Package in User-Panel to retriev...
304,545999,2026-05-16T19:30:00Z,FINISHED,34,REGULAR_SEASON,None,2026-05-26T00:20:43Z,[],2187,Portugal,...,Gil Vicente,GIL,https://crests.football-data.org/5533.png,HOME_TEAM,REGULAR,3,0,2,0,Activate Odds-Package in User-Panel to retriev...

In [24]:
# show what we really want
first_metric["homeTeam.name"].value_counts()

homeTeam.name
FC Porto                      11
Sport Lisboa e Benfica        10
Sporting Clube de Portugal     9
Sporting Clube de Braga        7
Gil Vicente FC                 5
FC Famalicão                   5
CD Santa Clara                 3
FC Alverca                     3
GD Estoril Praia               3
CF Estrela da Amadora          3
FC Arouca                      2
Rio Ave FC                     2
Vitória SC                     2
CD Tondela                     2
CD Nacional                    2
Casa Pia AC                    2
Moreirense FC                  1
AVS                            1
Name: count, dtype: int64

What we really want to see is the % of wins at HT that ended on a win at FT

In [25]:
#check, first, the amount of times that teams were winning at HT

first_metric_final = PPL_matches[PPL_matches["score.halfTime.home"] > PPL_matches["score.halfTime.away"]]
first_metric_final["homeTeam.name"].value_counts()

homeTeam.name
FC Porto                      12
Sport Lisboa e Benfica        11
Sporting Clube de Portugal    10
Sporting Clube de Braga        9
Casa Pia AC                    6
Gil Vicente FC                 6
FC Famalicão                   5
FC Arouca                      5
FC Alverca                     5
GD Estoril Praia               5
CF Estrela da Amadora          4
Rio Ave FC                     4
CD Nacional                    3
CD Santa Clara                 3
Vitória SC                     2
AVS                            2
CD Tondela                     2
Moreirense FC                  2
Name: count, dtype: int64

In [26]:
#Now see how many of those times ended up on winning at FT and put it on %

ab = (first_metric["homeTeam.name"].value_counts() / first_metric_final["homeTeam.name"].value_counts() * 100).round(1)
ab.sort_values(ascending=False)

homeTeam.name
CD Tondela                    100.0
CD Santa Clara                100.0
FC Famalicão                  100.0
Vitória SC                    100.0
FC Porto                       91.7
Sport Lisboa e Benfica         90.9
Sporting Clube de Portugal     90.0
Gil Vicente FC                 83.3
Sporting Clube de Braga        77.8
CF Estrela da Amadora          75.0
CD Nacional                    66.7
FC Alverca                     60.0
GD Estoril Praia               60.0
AVS                            50.0
Rio Ave FC                     50.0
Moreirense FC                  50.0
FC Arouca                      40.0
Casa Pia AC                    33.3
Name: count, dtype: float64

# **2nd METRIC** **MAIN** **CODE**

In [27]:
#turning the score around in the second half

#first is to see the turnarounds in the home games

second_metric_home = PPL_matches[(PPL_matches["score.halfTime.home"] < PPL_matches["score.halfTime.away"]) & (PPL_matches["score.winner"] == "HOME_TEAM")]

In [28]:
#second is to see the turnarouds in the away games

second_metric_away = PPL_matches[(PPL_matches["score.halfTime.away"] < PPL_matches["score.halfTime.home"]) & (PPL_matches["score.winner"] == "HOME_AWAY")]

In [29]:
#Let's count them
second_metric_home["homeTeam.name"].value_counts()

homeTeam.name
Vitória SC          2
GD Estoril Praia    1
FC Arouca           1
Gil Vicente FC      1
FC Alverca          1
CD Santa Clara      1
Moreirense FC       1
Name: count, dtype: int64

In [30]:
second_metric_home2 = PPL_matches[PPL_matches["score.halfTime.home"] < PPL_matches["score.halfTime.away"]]
second_metric_home2["homeTeam.name"].value_counts()

homeTeam.name
AVS                           7
CF Estrela da Amadora         7
FC Alverca                    7
Rio Ave FC                    7
FC Arouca                     6
Casa Pia AC                   5
GD Estoril Praia              5
Moreirense FC                 5
Gil Vicente FC                5
CD Tondela                    4
Sporting Clube de Braga       4
CD Nacional                   4
CD Santa Clara                4
Vitória SC                    3
FC Famalicão                  3
Sport Lisboa e Benfica        1
Sporting Clube de Portugal    1
Name: count, dtype: int64

In [31]:
bc = (second_metric_home["homeTeam.name"].value_counts() / second_metric_home2["homeTeam.name"].value_counts() * 100).round(1)
bc.sort_values(ascending=False)

homeTeam.name
Vitória SC                    66.7
CD Santa Clara                25.0
GD Estoril Praia              20.0
Gil Vicente FC                20.0
Moreirense FC                 20.0
FC Arouca                     16.7
FC Alverca                    14.3
AVS                            NaN
CD Nacional                    NaN
CD Tondela                     NaN
CF Estrela da Amadora          NaN
Casa Pia AC                    NaN
FC Famalicão                   NaN
Rio Ave FC                     NaN
Sport Lisboa e Benfica         NaN
Sporting Clube de Braga        NaN
Sporting Clube de Portugal     NaN
Name: count, dtype: float64

In [32]:
#no team could turnaround a result playing away
second_metric_away["awayTeam.name"].value_counts()

Series([], Name: count, dtype: int64)